feat: add bingo-elastic menu item and relevant documentation
epam/lifescience pull request #98
Opened 2023-02-01 23:00 UTC by MysterionRise

2023-02-01 23:00 UTC, MysterionRise commented
@AlexanderSavelyev could you please review and merge it?

2023-02-02 09:37 UTC, AlexanderSavelyev requested changes

2023-02-02 09:37 UTC, AlexanderSavelyev commented on README.md
> +# Lifescience Open Source portal documentation
please change back. It is more correct to spell "Lifesciences"

2023-02-02 10:59 UTC, MysterionRise commented
@AlexanderSavelyev updated, please review

2023-02-06 17:30 UTC, AlexanderSavelyev approved these changes

2023-02-06 17:30 UTC, merged